### ISSUE TITLE
请问有sql文件吗

### ISSUE THREAD

**Issue by Chancebaby** [ff202118/literary-website#1]
请问有sql文件吗

**Comment by ff202118** [comment]
我用的是Flask-SQLAlchemy，所以不用导入SQL文件，代码中已经包含了创建数据库模型的相关代码。
你需要以下步骤：
1）在settings.py中将SQLALCHEMY_DATABASE_URI = ***@***.***:3306/Web_DB'代码修改成你自己的Mysql密码和数据库模型
2）在Mysql中创建你上面的填写的数据库模型
3）在Powershell终端运行一下代码：
$env:FLASK_APP = "RealProject" $env:FLASK_ENV = "development" flask shell
4）继续在Powershell终端运行一下代码：
flask db init
flask db migrate flask db upgrade

FANG
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ff202118/literary-website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月12日(星期二) 下午4:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ff202118/literary-website] 请问有sql文件吗 (Issue #1)





 
请问有sql文件吗

**Comment by Chancebaby** [comment]
请问你的数据库中有多少个实体？数据库表有几个？

**Comment by Chancebaby** [comment]
我想查看一下你的数据库语句，因为我主要要完成数据库方面的设计。

**Comment by ff202118** [comment]
> 我想查看一下你的数据库语句，因为我主要要完成数据库方面的设计。

在models.py文件中，你可以去看一下。

**Comment by Chancebaby** [comment]
这是我的微信：dzqdzqdzq816，方便加一下交流一下吗？多谢！！

**Comment by Chancebaby** [comment]
没有相关数据，只有表结构是吗？






Chance
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ff202118/literary-website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月22日(星期五) 下午4:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ff202118/literary-website] 请问有sql文件吗 (Issue #1)





  
我想查看一下你的数据库语句，因为我主要要完成数据库方面的设计。
  
在models.py文件中，你可以去看一下。

**Comment by ff202118** [comment]
是的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月29日(周日) 晚上7:46
收件人: ***@***.***&gt;;
抄送: "Jiaqi ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ff202118/literary-website] 请问有sql文件吗 (Issue #1)




 没有相关数据，只有表结构是吗？ 
 
 
 
 
 
 
 Chance 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ff202118/literary-website"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年11月22日(星期五) 下午4:21 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ff202118/literary-website] 请问有sql文件吗 (Issue #1) 
 
 
 
 
 
    
 我想查看一下你的数据库语句，因为我主要要完成数据库方面的设计。 
    
 在models.py文件中，你可以去看一下。

**Comment by Chancebaby** [comment]
请问管理员的账号密码是什么




Chance
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ff202118/literary-website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月13日(星期三) 中午11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ff202118/literary-website] 请问有sql文件吗 (Issue #1)





 我用的是Flask-SQLAlchemy，所以不用导入SQL文件，代码中已经包含了创建数据库模型的相关代码。 
 你需要以下步骤： 
 1）在settings.py中将SQLALCHEMY_DATABASE_URI = ***@***.***:3306/Web_DB'代码修改成你自己的Mysql密码和数据库模型 
 2）在Mysql中创建你上面的填写的数据库模型 
 3）在Powershell终端运行一下代码： 
 $env:FLASK_APP = "RealProject" $env:FLASK_ENV = "development" flask shell 
 4）继续在Powershell终端运行一下代码： 
 flask db init 
 flask db migrate flask db upgrade 
 
 FANG 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ff202118/literary-website"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年11月12日(星期二) 下午4:02 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[ff202118/literary-website] 请问有sql文件吗 (Issue #1) 
 
 
 
 
 
   
 请问有sql文件吗

**Comment by ff202118** [comment]
账号是admin
密码好像是123
如果密码不对，你可以自己创建一个



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月30日(周一) 中午12:03
收件人: ***@***.***&gt;;
抄送: "Jiaqi ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ff202118/literary-website] 请问有sql文件吗 (Issue #1)




 请问管理员的账号密码是什么 
 
 
 
 
 Chance 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ff202118/literary-website"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年11月13日(星期三) 中午11:19 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ff202118/literary-website] 请问有sql文件吗 (Issue #1) 
 
 
 
 
 
  我用的是Flask-SQLAlchemy，所以不用导入SQL文件，代码中已经包含了创建数据库模型的相关代码。  
  你需要以下步骤：  
  1）在settings.py中将SQLALCHEMY_DATABASE_URI = ***@***.***:3306/Web_DB'代码修改成你自己的Mysql密码和数据库模型  
  2）在Mysql中创建你上面的填写的数据库模型  
  3）在Powershell终端运行一下代码：  
  $env:FLASK_APP = "RealProject" $env:FLASK_ENV = "development" flask shell  
  4）继续在Powershell终端运行一下代码：  
  flask db init  
  flask db migrate flask db upgrade  
   
  FANG  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ff202118/literary-website"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2024年11月12日(星期二) 下午4:02  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[ff202118/literary-website] 请问有sql文件吗 (Issue #1)  
   
   
   
   
   
     
  请问有sql文件吗

**Comment by Chancebaby** [comment]
文章审核的界面好像找不到，请问应该在哪里进入



---原始邮件---
发件人: "Jiaqi ***@***.***&gt;
发送时间: 2024年12月30日(周一) 中午12:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ff202118/literary-website] 请问有sql文件吗 (Issue #1)




 账号是admin 
 密码好像是123 
 如果密码不对，你可以自己创建一个 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年12月30日(周一) 中午12:03 
 收件人: ***@***.***&amp;gt;; 
 抄送: "Jiaqi ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [ff202118/literary-website] 请问有sql文件吗 (Issue #1) 
 
 
 
 
  请问管理员的账号密码是什么  
   
   
   
   
  Chance  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ff202118/literary-website"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2024年11月13日(星期三) 中午11:19  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ff202118/literary-website] 请问有sql文件吗 (Issue #1)  
   
   
   
   
   
   我用的是Flask-SQLAlchemy，所以不用导入SQL文件，代码中已经包含了创建数据库模型的相关代码。   
   你需要以下步骤：   
   1）在settings.py中将SQLALCHEMY_DATABASE_URI = ***@***.***:3306/Web_DB'代码修改成你自己的Mysql密码和数据库模型   
   2）在Mysql中创建你上面的填写的数据库模型   
   3）在Powershell终端运行一下代码：   
   $env:FLASK_APP = "RealProject" $env:FLASK_ENV = "development" flask shell   
   4）继续在Powershell终端运行一下代码：   
   flask db init   
   flask db migrate flask db upgrade   
     
   FANG   
   ***@***.***   
     
     
     
   &amp;amp;amp;nbsp;   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "ff202118/literary-website"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2024年11月12日(星期二) 下午4:02   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;[ff202118/literary-website] 请问有sql文件吗 (Issue #1)   
     
     
     
     
     
       
   请问有sql文件吗
